### ISSUE TITLE
Contributor images are broken. :( 

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/labs#90]
https://labs.moduscreate.com/capsule-aws-static-web-app-service

https://labs.moduscreate.com/beep-vue-ionic-hybrid-mobile-app

Looks like team images are broken. :( 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/180031/123109735-79e86680-d409-11eb-82fd-1345accf4d7f.png">

**Comment by crissoca** [comment]
looks like some rules need to be updated, under `Content Security Policy` directive: `img-src` we need to add `unavatar.vercel.app`

**Comment by rodriguezmanu** [comment]
could be, I am wondering if could be relative to this change https://github.com/ModusCreateOrg/labs/pull/77/files, probably is not working escape quotes

**Comment by crissoca** [comment]
The way gatsby works is that you can create rules or security policies the problem here is that the third party service we use to get the Twitter images is now serving images using a new url, we already have `unavatar.now.sh` under that set of rules so it's just a matter of adding the new url it's using to serve the images and we should be ok.
